import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import Navbar from "./components/Navbar";
import 'bootstrap/dist/css/bootstrap.css';
import '@fortawesome/fontawesome-svg-core/styles.css';

export const metadata: Metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="assets/js/jquery-3.6.0.min.js" strategy="beforeInteractive"></Script>
      </head>
      <body id="body">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
